# Generated by Django 3.0.4 on 2021-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
