# Generated by Django 3.0.4 on 2020-12-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_productimage_img_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cart_id", models.CharField(max_length=50)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "CartItem",
                "verbose_name_plural": "CartItems",
            },
        ),
    ]
