# Generated by Django 3.0.4 on 2021-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_userprofile_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("VE", "Vendor"), ("BU", "Buyer")], default="VE", max_length=30
            ),
        ),
    ]
