# Generated by Django 3.0.4 on 2021-01-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
