# Generated by Django 3.0.4 on 2021-01-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_auto_20210114_0919"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
    ]
