# Generated by Django 3.0.4 on 2021-01-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "OrderItem", "verbose_name_plural": "OrderItems"},
        ),
    ]
